<script setup lang="ts">
import { useAuthStore } from '@/stores'
import { ref, onMounted, onBeforeMount } from 'vue'


onMounted(async () => {
  const authStore = useAuthStore()
})

</script>

<template>
    <v-container>
      <v-row>
        <v-col>
          <h1>D2AI Studio</h1>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <hr class="mt-3">
          <h2>Market research report generation </h2>
          The experimental report generator (agent) generates market reports from topics. <br>
          <a href="/market-research" target="_blank" rel="noopener noreferrer">Market Research</a> has the example reports generated by the agent. 
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <hr class="mt-3">
          <h2 class="mt-3">Time series data analysis</h2>
          Active project to analyze time series data and work on tasks.<br>
          It trains sensor data, uses the generated model for generative tasks. <br>
          Tasks include (not limited to) forecasting, anomaly detection, and classification. 
        </v-col>
      </v-row>
      
    </v-container>
</template>