<script setup lang="ts">
import { useAuthStore } from '@/stores'
import { ref, onMounted, onBeforeMount } from 'vue'


onMounted(async () => {
  const authStore = useAuthStore()
})

</script>

<template>
    <v-container>
      <h1>D2AI Studio</h1>
      <h2>Market research paper generator </h2>
      <div>
        The experimental report generator (agent) generates market reports for the requested topics. <br>
        Page <a href="/market-research" target="_blank" rel="noopener noreferrer">Market Research</a> has the example reports generated by this agent. 
      </div>

      <h2 class="mt-3">Time series data modeling service</h2>
      <div>
        On going project to provide services of modeling and tasks specific for time series data.<br>
        It does the analysis of the sensor data - modeling, and uses the generated models for various tasks. <br>
        The tasks include (not limited to) forecasting, anomaly detection, and classification. 
      </div>
      
    </v-container>
</template>